CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_TBL_MEMBER PRIMARY KEY,
	MEMBER_EMAIL VARCHAR2(255) NOT NULL UNIQUE,
	MEMBER_PASSWORD VARCHAR2(255),
	MEMBER_ADDRESS VARCHAR2(255),
	MEMBER_RECOMENDER_EMAIL VARCHAR2(255)
	);

SELECT * FROM TBL_MEMBER;

UPDATE TBL_MEMBER 
SET MEMBER_RECOMENDER_EMAIL = 'hong1234@gmail.com'
WHERE ID = 2;

UPDATE TBL_MEMBER 
SET MEMBER_RECOMENDER_EMAIL = 'hong1234@gmail.com'
WHERE ID = 3;

UPDATE TBL_MEMBER 
SET MEMBER_RECOMENDER_EMAIL = 'kim7897@gmail.com'
WHERE ID = 1;

SELECT * FROM TBL_MEMBER;