
CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_EMAIL VARCHAR2(255) NOT NULL UNIQUE,
	MEMBER_PASSWORD VARCHAR2(255) NULL,
	MEMBER_NAME VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) UNIQUE NULL,
	PRODUCT_PRICE NUMBER NOT NULL,
	PRODUCT_STOCK NUMBER NULL
);

CREATE SEQUENCE SEQ_ORDER;
CREATE TABLE TBL_ORDER(
	ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
	ORDER_COMMENT VARCHAR2(255) NULL,
	ORDER_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MEMBER_ID NUMBER,
	PRODUCT_ID NUMBER,
	CONSTRAINT FK_ORDER_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_ORDER_PRODUCT FOREIGN KEY(PRODUCT_ID)
	REFERENCES TBL_PRODUCT(ID)
);

--게시글(TBL_POST)
--- 게시글 제목, 게시글 내용, 게시글 작성 시간

--멤버(TBL_MEMBER)
--테이블을 ERD에 설계하고, 
--테이블 간의 관계를 생각하여 관계를 맺은 후 DDL하시오..

CREATE SEQUENCE SEQ_POST;
CREATE TABLE TBL_POST(
	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
	POST_TITLE VARCHAR2(255) NOT NULL,
	POST_IN VARCHAR2(255) NOT NULL,
	POST_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MEMBER_ID NUMBER,
	CONSTRAINT FK_POST_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID)
);

CREATE SEQUENCE SEQ_REPLY;
CREATE TABLE TBL_REPLY(
	ID NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,	
	REPLY_IN VARCHAR2(255) NOT NULL,
	REPLY_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	POST_ID NUMBER,
	CONSTRAINT FK_REPLY_POST FOREIGN KEY(POST_ID)
	REFERENCES TBL_POST(ID)
);


/*
   요구사항
   유치원을 하려고 하는데, 아이들이 체험학습 프로그램을 신청해야 합니다.
   아이들 정보는 이름, 나이, 성별이 필요하고 학부모는 이름, 나이, 주소, 전화번호, 성별이 필요해요
   체험학습은 체험학습 제목, 체험학습 내용, 이벤트 이미지 여러 장이 필요합니다.
   아이들은 여러 번 체험학습에 등록할 수 있어요.
   
*/


-- 등록

-- 신청FK 
-- 아이 - 신청 - 체험학습 


-- 유치원
--CREATE SEQUENCE SEQ_KINDERGARDEN;
CREATE TABLE KINDERGARDEN(
	ID NUMBER CONSTRAINT PK_KINDERGARDEN PRIMARY KEY,
	KINDERGARDEN_NAME VARCHAR2(255)
);
-- 아이1 - 부모N
-- 아이들 정보는 이름, 나이, 성별이 필요하고
CREATE SEQUENCE SEQ_KINDER;
CREATE TABLE KINDER(
	ID NUMBER CONSTRAINT PK_KINDER PRIMARY KEY,
	KINDER_NAME VARCHAR2(255) NOT NULL,
	KINDER_AGE NUMBER NOT NULL,
	KINDER_GENDER VARCHAR2(255) NOT NULL
	KINDERGARDEN_ID NUMBER,
	CONSTRAINT FK_KINDER_KINDERGARDEN FOREIGN KEY(KINDERGARDEN_ID)
	REFERENCES TBL_KINDERGARDEN(ID)
);

-- 학부모는 이름, 나이, 주소, 전화번호, 성별
CREATE SEQUENCE SEQ_KINDER_PARENTS;
CREATE TABLE KINDER_PARENTS(
	ID NUMBER CONSTRAINT PK_KINDER_PARENTS PRIMARY KEY,
	KINDER_PARENTS_NAME VARCHAR2(255) NOT NULL,
	KINDER_PARENTS_AGE NUMBER NOT NULL,
	KINDER_PARENTS_ADDRESS VARCHAR2(255) UNIQUE NOT NULL,
	KINDER_PARENTS_PHONE NUMBER UNIQUE NOT NULL,
	KINDER_PARENTS_GENDER VARCHAR2(255) NOT NULL,
	KINDERGARDEN_ID NUMBER,
	CONSTRAINT FK_KINDER_PARENTS_KINDERGARDEN FOREIGN KEY(KINDERGARDEN_ID)
	REFERENCES TBL_KINDERGARDEN(ID)
);

-- 체험학습1 - 이미지N
-- 체험학습은 체험학습 제목, 체험학습 내용, 이벤트 이미지 여러 장이 필요
CREATE SEQUENCE SEQ_FIELD_TRIP;
CREATE TABLE FIELD_TRIP(
	ID NUMBER CONSTRAINT PK_FIELD_TRIP PRIMARY KEY,
	FIELD_TRIP_TITLE VARCHAR2(255) NOT NULL,
	FIELD_TRIP_CONTENT VARCHAR2(255) NOT NULL,
	FIELD_TRIP_EVENT VARCHAR2(255) NOT NULL,
	KINDER_ID NUMBER,
	CONSTRAINT FK_FIELD_TRIP_KINDER FOREIGN KEY(KINDER_ID)
	REFERENCES TBL_KINDER(ID)
);



/*

   요구사항
   안녕하세요, 광고 회사를 운영하려고 준비중인 사업가입니다.
   광고주는 기업이고 기업 정보는 이름, 주소, 대표번호, 기업종류(스타트업, 중소기업, 중견기업, 대기업)입니다.
   광고는 제목, 내용이 있고 기업은 여러 광고를 신청할 수 있습니다.
   기업이 광고를 선택할 때에는 카테고리로 선택하며, 대카테고리, 중카테고리, 소카테고리가 있습니다.

*/


-- 광고회사운영사업가

-- 광고주 == 기업 / 정보
-- 광고주는 기업이고 기업 정보는 이름, 주소, 대표번호, 기업종류(스타트업, 중소기업, 중견기업, 대기업)
CREATE SEQUENCE SEQ_AD_CLIENT;
CREATE TABLE TBL_AD_CLIENT(
	ID NUMBER CONSTRAINT PK_AD_CLIENT PRIMARY KEY,
	AD_CLIENT_NAME VARCHAR2(255) NOT NULL UNIQUE,
	AD_CLIENT_ADDRESS VARCHAR2(255) NOT NULL,
	AD_CLIENT_MAIN_NUM NUMBER UNIQUE NOT NULL,
	AD_CLIENT_TYPE VARCHAR2(255) NOT NULL,
	CONSTRAINT AD_CLIENT_BEN_TYPE CHECK (AD_CLIENT_TYPE IN('스타트업, 중소기업, 중견기업, 대기업')
);


-- 광고는 제목, 내용
CREATE SEQUENCE SEQ_AD;
CREATE TABLE TBL_AD(
	ID NUMBER CONSTRAINT PK_AD PRIMARY KEY,
	AD_TITLE VARCHAR2(255) NOT NULL,
	AD_CONTENT VARCHAR2(255) NOT NULL

);

-- 신청 (기업은 여러 광고를)
CREATE SEQUENCE SEQ_AD_APPLY;
CREATE TABLE TBL_AD_APPLY(
	ID NUMBER CONSTRAINT PK_AD_APPLY PRIMARY KEY,
	AD_CLIENT_ID NUMBER,
	AD_ID NUMBER,
	CONSTRAINT FK_AD_APPLY_AD_CLIENT FOREIGN KEY(AD_CLIENT_ID)
	REFERENCES TBL_AD_CLIENT(ID),
	CONSTRAINT FK_AD_APPLY_AD FOREIGN KEY(AD_ID)
	REFERENCES TBL_AD(ID)
	
);

-- 광고카테고리 대카테고리, 중카테고리, 소카테고리
CREATE SEQUENCE SEQ_AD_CA_A;
CREATE TABLE TBL_AD_CA_A(
	ID NUMBER CONSTRAINT PK_AD_CA_A PRIMARY KEY,
	AD_CA_A_NAME VARCHAR2(255) NOT NULL,
	AD_ID NUMBER,
	CONSTRAINT FK_AD_CA_A_AD FOREIGN KEY(AD_ID)
	REFERENCES TBL_AD(ID)
);

-- 중카테고리
CREATE SEQUENCE SEQ_AD_CA_B;
CREATE TABLE TBL_AD_CA_B(
	ID NUMBER CONSTRAINT PK_AD_CA_B PRIMARY KEY,
	AD_CA_B_NAME VARCHAR2(255) NOT NULL,
	AD_CA_A_ID NUMBER,
	CONSTRAINT FK_AD_CA_B_AD_CA_A FOREIGN KEY(AD_CA_A_ID)
	REFERENCES TBL_AD_CA_A(ID)
);

-- 소카테고리
CREATE SEQUENCE SEQ_AD_CA_C;
CREATE TABLE TBL_AD_CA_C(
	ID NUMBER CONSTRAINT PK_AD_CA_C PRIMARY KEY,
	AD_CA_C_NAME VARCHAR2(255) NOT NULL,
	AD_CA_B_ID NUMBER,
	CONSTRAINT FK_AD_CA_C_AD_CA_B FOREIGN KEY(AD_CA_B_ID)
	REFERENCES TBL_AD_CA_B(ID)
);






























