
/*
 * GROUP BY부터 생각을 많이 해야한다.
 * FROM -> WHERE -> GROUP BY -> HAVING -> SELECT > ORDER BY
 * 
*/

SELECT * FROM TBL_REPLY;
SELECT * FROM TBL_POST;
SELECT * FROM TBL_USER;


SELECT TBP.*, TBU.USER_EMAIL  
FROM TBL_POST TBP
JOIN TBL_USER TBU
ON TBP.USER_ID = TBU.ID;

-- FK키 여러번이여도 목적에 맞게

SELECT TBR.REPLY_CONTENT, TBP.POST_TITLE 
FROM TBL_REPLY TBR
JOIN TBL_POST TBP
ON TBR.POST_ID = TBP.ID;

-- 댓글 테이블, 유저 테이블 조인 후
-- 댓글의 작성자와 댓글 내용을 조회

--SELECT TBR.REPLY_CONTENT, TBU.USER_EMAIL 
--FROM TBL_REPLY TBR
--JOIN TBL_USER TBU
--ON TBR.REPLY_CONTENT = TBU.ID;

-- 3개 JOIN
-- 게시글 제목, 댓글 내용, 작성자 
SELECT TBP.POST_TITLE, TBR.REPLY_CONTENT, TBU.USER_EMAIL 
FROM TBL_REPLY TBR
JOIN TBL_USER TBU 
ON TBR.USER_ID = TBU.ID
JOIN TBL_POST TBP
ON TBR.POST_ID = TBP.ID
-- 조건
WHERE POST_TITLE LIKE '%유중의 미%';


-- 중복제거

SELECT DISTINCT TBP.POST_TITLE
FROM TBL_REPLY TBR
JOIN TBL_USER TBU 
ON TBR.USER_ID = TBU.ID
JOIN TBL_POST TBP
ON TBR.POST_ID = TBP.ID
WHERE POST_TITLE LIKE '%유중의 미%';



--댓글이 2개이상 달린 게시글의 작성자 이메일, 주소를 조회하기
SELECT * FROM TBL_POST;

SELECT *
FROM TBL_POST TBP
JOIN (
	SELECT POST_ID
	FROM TBL_REPLY
	GROUP BY POST_ID
	HAVING COUNT(POST_ID) >= 2
	) TBR
ON TBP.ID = TBR.POST_ID;

-- 같은풀이
SELECT DISTINCT TBU.USER_EMAIL, TBU.USER_ADDRESS
FROM (
   SELECT POST_ID 
   FROM TBL_REPLY
   GROUP BY POST_ID
   HAVING COUNT(POST_ID) >= 2
) TBR
JOIN TBL_POST TBP
ON TBR.POST_ID = TBP.ID
JOIN TBL_USER TBU 
ON TBP.USER_ID = TBU.ID;


-- 내용에 뀨트북이 들어간 게시글의 달린 댓글 조회
SELECT *  
FROM TBL_REPLY
WHERE ID IN(
	SELECT POST_ID 
	FROM TBL_POST
	WHERE POST_TITLE LIKE '%뀨트북%' AND POST_CONTENT LIKE '%뀨트북%'
);


-- 내용에 포도가 들어간 글을 작성한 작성자의 이메일 조회
SELECT * FROM TBL_POST;

SELECT USER_EMAIL 
FROM TBL_USER
WHERE ID IN (
	SELECT ID 
	FROM TBL_POST
	WHERE POST_CONTENT LIKE '%포도%'
);


-- 2000년생 유저가 작성한 댓글 조회
SELECT * 
FROM TBL_REPLY
WHERE USER_ID IN(
	SELECT ID 
	FROM TBL_USER
	WHERE USER_BIRTH = 2000
);


-- 가장 나이가 어린 사용자가 작성한 게시글 조회

SELECT * FROM TBL_POST;


SELECT POST_CONTENT 
FROM TBL_POST
WHERE ID IN (
	SELECT USER_ID 
	FROM TBL_USER
	WHERE USER_BIRTH = (
		SELECT MAX(USER_BIRTH) 
		FROM TBL_USER
		)
);


-- 주소가 '구'로 끝나는 유저가 작성한 게시글에 달린 모든 댓글 조회

SELECT *
FROM TBL_REPLY TBR
JOIN (
	SELECT POST_CONTENT 
	FROM TBL_POST
	WHERE ID IN (
		SELECT USER_ID  
		FROM TBL_USER
		WHERE USER_ADDRESS LIKE '%구%'
		)
	) TBP
ON TBR.ID = TBP.POST_ID;


-- 평균 댓글 개수보다 작게 달린 게시글을 작성한 유저 조회
-- 유저 조회

SELECT * 
FROM TBL_POST TBP
JOIN (
	SELECT * 
	FROM TBL_USER
	WHERE ID IN (
			-- 작은댓글
			SELECT MIN(POST_ID) 
			FROM (
				SELECT COUNT(POST_ID) "POST_ID" 
				FROM TBL_REPLY
				GROUP BY POST_ID
				
				)
			-- 평균댓글
			SELECT AVG(POST_COUNT) 
			FROM (
				-- 갯수
				SELECT COUNT(POST_ID) "POST_COUNT"
				FROM TBL_REPLY
				GROUP BY POST_ID 
				)
		)
) TBR
ON TBR.POST_ID = TBP.ID;













