SELECT * FROM DUAL;

CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) NOT NULL,
	PRODUCT_PRICE NUMBER DEFAULT 0,
	PRODUCT_STOCK NUMBER DEFAULT 999
);

SELECT * FROM TBL_PRODUCT;

DELETE FROM TBL_PRODUCT
WHERE ID = 6;

UPDATE TBL_PRODUCT 
SET PRODUCT_NAME = '상품1', PRODUCT_PRICE = '70000', PRODUCT_STOCK = 20
WHERE ID = 1;

SELECT ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_STOCK  
FROM TBL_PRODUCT
ORDER BY ASC ;