SELECT * FROM DUAL;

CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) NOT NULL,
	PRODUCT_PRICE NUMBER DEFAULT 0,
	PRODUCT_STOCK NUMBER DEFAULT 999
);

SELECT ID,  PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_STOCK
FROM TBL_PRODUCT
ORDER BY ID DESC ;

SELECT * FROM TBL_PRODUCT;



SELECT ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_STOCK
FROM TBL_PRODUCT
WHERE ID = 6;

SELECT * FROM TBL_PRODUCT;

UPDATE TBL_PRODUCT 
SET PRODUCT_NAME = '키보드', PRODUCT_PRICE = 50000, PRODUCT_STOCK = 5
WHERE ID = 1;

DELETE FROM TBL_PRODUCT
WHERE ID = 3;

CREATE SEQUENCE SEQ_POST;
CREATE TABLE TBL_POST(
	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
	POST_TITLE VARCHAR2(255) NOT NULL,
	POST_CONTENT VARCHAR2(255) NOT NULL,
	POST_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE SEQ_ORDER;
CREATE TABLE TBL_ORDER(
   ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
   ORDER_COUNT NUMBER DEFAULT 1,
   PRODUCT_ID NUMBER,
   MEMBER_ID NUMBER,
   CONSTRAINT FK_ORDER_PRODUCT FOREIGN KEY(PRODUCT_ID)
   REFERENCES TBL_PRODUCT(ID),
   CONSTRAINT FK_ORDER_MEMBER FOREIGN KEY(MEMBER_ID)
   REFERENCES TBL_MEMBER(ID)
);

SELECT 
	TBO.ID, TBO.ORDER_COUNT, TBO.PRODUCT_ID, TBO.MEMBER_ID, TBO.ORDER_COUNT * TBP.PRODUCT_PRICE TOTAL_PRICE,
	TBM.MEMBER_EMAIL, TBM.MEMBER_NAME,
	TBP.PRODUCT_NAME, TBP.PRODUCT_PRICE, TBP.PRODUCT_STOCK 
FROM TBL_ORDER TBO
JOIN TBL_MEMBER TBM
ON TBO.MEMBER_ID = TBM.ID
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID;



INSERT INTO TBL_POST
VALUES(SEQ_USER.NEXTVAL, '타이틀', '내용') ;

SELECT ID, POST_TITLE, POST_CONTENT, TO_CHAR(POST_CREATE_AT, 'YYYY-MM-DD') POST_CREATE_AT
FROM TBL_POST
ORDER BY ID ASC;

SELECT ID, POST_TITLE, POST_CONTENT, POST_CREATE
FROM TBL_POST
WHERE ID = 1;

UPDATE TBL_POST 
SET POST_TITLE = '키보드', POST_CONTENT = , POST_CREATE_AT
WHERE ID = 1;

DELETE FROM TBL_POST
WHERE ID = 1;

SELECT * FROM TBL_POST;


CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_EMAIL VARCHAR2(255) NOT NULL,
	MEMBER_PASSWORD VARCHAR2(255) NOT NULL,
	MEMBER_NAME VARCHAR2(255)
);

SELECT ID, MEMBER_EMAIL, MEMBER_PASSWORD, MEMBER_NAME
FROM TBL_POST
WHERE ID = 1;

COUNT

SELECT COUNT(*) IS_EXISTS
FROM TBL_MEMBER
WHERE MEMBER_EMAIL = '';

SELECT * FROM TBL_MEMBER;

INSERT INTO TBL_PRODUCT 
VALUES(SEQ_PRODUCT.NEXTVAL, '노트북', 20000,	20) ;

SELECT ID, PRODUCT_NAME , PRODUCT_PRICE , PRODUCT_STOCK 
FROM TBL_PRODUCT
ORDER BY ID DESC;

SELECT ID, PRODUCT_NAME , PRODUCT_PRICE , PRODUCT_STOCK 
FROM TBL_PRODUCT
WHERE ID = 1;

SELECT * FROM TBL_PRODUCT;

UPDATE TBL_PRODUCT 
SET PRODUCT_NAME = '' 
WHERE ID = 5;

DELETE FROM TBL_PRODUCT
WHERE ID = 1;

SELECT * FROM TBL_PRODUCT;

SELECT * FROM TBL_ORDER;
SELECT ID
FROM TBL_MEMBER
WHERE MEMBER_EMAIL = '';

INSERT INTO TBL_ORDER
VALUES(SEQ_ORDER.NEXTVAL, 1, 1,	1);

SELECT ID, PRODUCT_ID, MEMBER_ID  
FROM TBL_ORDER;

SELECT PRODUCT_NAME, PRODUCT_STOCK  
FROM TBL_PRODUCT;

UPDATE TBL_PRODUCT
SET PRODUCT_STOCK = PRODUCT_STOCK - 1
WHERE ID = 1;

SELECT * FROM TBL_ORDER;
SELECT * FROM TBL_PRODUCT;






