--인터프리트 언어
-- 마지막에 ;
-- 대문자 사용/갈색 명령어 / 

SELECT SYSDATE FROM DUAL;

-- 주석 Ctrl + /
-- 한줄 복사 Ctrl + alt + 
-- 줄바꿈 Ctrl + shift +
-- 삭제 Ctrl + d
-- 한 줄 실행 Ctrl + Enter

-- DDL 언어
--CREATE TABLE 테이블명(
--	컬럼명 타입 제약조건1 제약조건2,
--	컬럼명 타입 제약조건1 제약조건2,
--	컬럼명 타입 제약조건1 제약조건2
--);

-- 예약어 사용X
-- TBL_ : 테이블
-- 스네이크 표기법
CREATE TABLE TBL_TEST(
	ID NUMBER CONSTRAINT PK_TEST PRIMARY KEY,
	TEST_NAME VARCHAR2(255),
	TEST_AGE NUMBER
);

SELECT ALL * FROM TBL_TEST;

-- 동물
-- 이름NAME 나이AGE 종류SPECIES 생일BRITH-DAY
CREATE TABLE TBL_ANIMAL(
	ID NUMBER CONSTRAINT PK_ANIMAL PRIMARY KEY,
	ANIMAL_NAME VARCHAR2(255),
	ANIMAL_AGE NUMBER,
	ANIMAL_SPECIES VARCHAR2(255),
	ANIMAL_BRITH_DAY DATE
);

SELECT ALL * FROM TBL_ANIMAL;

-- 게시판POST
-- 글제목TITLE 글내용CONTENT 작성시간CREATE_AT

-- DML - CREATE 
CREATE SEQUENCE SEQ_POST;
CREATE TABLE TBL_POST(
	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
	POST_TITLE VARCHAR2(255),
	POST_CONTENT VARCHAR2(255),
	POST_CREATE_AT DATE
);

SELECT ALL * FROM TBL_POST;

-- ALTER 
-- 컬럼 추가(ADD)

-- 먹이 컬럼 추가 (FEED)
--ALTER TABLE TBL_ANIMAL ADD 컬럼명 타입;
ALTER TABLE TBL_ANIMAL ADD ANIMAL_FEED VARCHAR2(255);


-- 컬럼 변경(MODIFY)
ALTER TABLE TBL_ANIMAL MODIFY ANIMAL_FEED NUMBER;
ALTER TABLE TBL_ANIMAL ADD ANIMAL_FEED VARCHAR2(255);

-- BRITH_DAY -> TIMESTAMP
ALTER TABLE TBL_ANIMAL MODIFY ANIMAL_BRITH_DAY TIMESTAMP;

-- 컬럼명 변경(RENAME COLUMN 기존 컬럼명 TO 바꿀 컬럼명)
-- BRITH_DAY -> BRITH
ALTER TABLE TBL_ANIMAL RENAME COLUMN ANIMAL_BRITH_DAY TO ANIMAL_BRITH;
ALTER TABLE TBL_ANIDFK RENAME COLUMN ANUMAL_FDJF TO DKFSKFJ;


-- ANIMAL_NAME -> ANIMAL_OWNER
ALTER TABLE TBL_ANIMAL RENAME COLUMN ANIMAL_NAME TO AMIMAL_OWNER;

-- TBL ANIMAL -> TBL_PERSON
-- 테이블 이름바꿈 RENAME TO
ALTER TABLE TBL_ANIMAL RENAME TO TBL_PERSON;


SELECT ALL * FROM TBL_PERSON;
SELECT ALL * FROM TBL_ANIMAL;


-- DROP : 테이블 전체
-- DROP TABLE : 테이블 이름;
-- DROP AEQUENCE : 시퀀스 이름;
DROP TABLE TBL_TEST;
SELECT ALL * FROM TBL_TEST;

-- TRUNCATE 테이블이 만들어졌을 때 최조 상태로 되돌리는 키워드 
TRUNCATE TABLE TBL_ANIMAL;
SELECT ALL * FROM TBL_ANIMAL;


-- 테이블 생성 + 제약 조건
-- TBL_USER
-- ID, USER_EMAIL, USER_PASSWORD, USER_NAME, USER_PHONE, USER_CREATE_AT
-- CURRENT_TIMESTAMP : 현재시간
CREATE SEQUENCE SEQ_USER;
CREATE TABLE TBL_USER(
	ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_EMAIL VARCHAR2(255) UNIQUE NOT NULL,
	USER_PASSWORD VARCHAR2(255) NOT NULL,
	USER_NAME VARCHAR2(255),
	USER_PHONE VARCHAR2(255) NOT NULL,
	USER_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT ALL * FROM TBL_USER;

-- 자동차(CAR) 테이블
-- 이름(NAME) 브랜드(BRAND) 가격(PRICE) 컬러(COLOR) 인승(SEATER) 출고일자(CREATE_AT)
-- 제약 조건	
-- ADD 추가 RENAME COLUMN DFFD TO DFDFD 이름바꿈 DROP 삭제 타입변경 MODIFY
 

CREATE SEQUENCE SEQ_CAR;
CREATE TABLE TBL_CAR(
	ID NUMBER CONSTRAINT PK_CAR PRIMARY KEY,
	CAR_NAME VARCHAR2(255) NOT NULL,
	CAR_BRAND VARCHAR2(255) NOT NULL,
	CAR_PRICE NUMBER DEFAULT 0,
	CAR_COLOR VARCHAR2(255) NOT NULL,
	CAR_SEATER NUMBER DEFAULT 4,
	CAR_CREATE_AT DATE DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM TBL_CAR;

-- 1. CAR_NAME
-- 컬럼 이름 변경 -> CAR_MODEL
--ALTER TABLE TBL_CAR RENAME COLUMN CAR_NAME TO CAR_MODEL;

-- 2. CAR_PRICE
-- 컬럼 타입 변경 -> VARCHAR2(255)
ALTER  TABLE TBL_CAR MODIFY CAR_PRICE VARCHAR2(255);

-- 3. CAR_COLOR
-- 컬럼 삭제
ALTER TABLE TBL_CAR DROP COLUMN CAR_COLOR;

SELECT ALL * FROM TBL_CAR;


-- 제약조건 수정
-- NOT NULL, UNIQUE
--NOT NULL -> NULL 허용으로 변경
ALTER TABLE TBL_CAR MODIFY CAR_MODEL NULL;
ALTER TABLE TBL_CAR MODIFY CAR_MODEL NOT NULL;


-- DEFAULT 추가 삭제 수정
-- CAR_BRAND
-- 오라클은 값은 ''(싱글쿼터, 홑 따옴표)
ALTER TABLE TBL_CAR MODIFY CAR_BRAND DEFAULT '블랙';

-- 기존 값을 그대로 변경
ALTER TABLE TBL_CAR MODIFY CAR_BRAND DEFAULT '레드';

-- 삭제
ALTER TABLE TBL_CAR MODIFY CAR_BRAND DEFAULT NULL;


-- ADD CONSTRAINT
-- UNIQUE
-- CAR_MODEL에 UNIQUE 추가
ALTER TABLE TBL_CAR ADD CONSTRAINT PK_CAR UNIQUE (CAR_MODEL);

-- CAR MODEL에 UNIQUE 삭제
ALTER TABLE TBL_CAR DROP CONSTRAINT UK_CAR;

--ex)
--ALTER TABLE TBL_CAR ADD CONSTRAINT PK_CAR PRIMARY KEY(ID);



-- CAR_SEATER DEFAULT 값을 8로 변경
CREATE TABLE TBL_CAR MODIFY CAR_SEATER DEFAULT 8;

-- CAR_BRAND UNIQUE 추가
--ALTER TABLE TBL_CAR ADD CONSTRAINT UK_CAR_BRAND UNIQUE (CAR_BRAND);
--ALTER TABLE TBL_CAR DROP CONSTRAINT UK_CAR_BRAND;


-- FK KEY 없는 테이블 먼저 만들기
-- 관계
-- 유저TBL_USER/구매 테이블 설계
CREATE SEQUENCE SEQ_USER;
CREATE TABLE TBL_USER(
	ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_NAME VARCHAR2(255) NOT NULL,
	USER_ADDRESS VARCHAR2(255) NOT NULL,
	USER_PHONE VARCHAR2(255) DEFAULT '010-0000-0000'
);

CREATE SEQUENCE SEQ_ORDER;
CREATE TABLE TBL_ORDER(
	ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
	ORDER_PRDUCK VARCHAR2(255) NOT NULL,
	ORDER_STOCK NUMBER DEFAULT 1,
	USER_ID NUMBER,
	CONSTRAINT FK_ORDER_USER FOREIGN KEY(USER_ID)
	REFERENCES TBL_USER(ID)
);

-- 정규화
-- 상품 테이블(TBL_PRODUCT)
-- 상품 이름, 상품 가격, 상품 재고

-- 선물 테이블(TBL_GIFT)
-- 선물주소, 선물 수량, 상품의 아이디

CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) NOT NULL UNIQUE,
	PRODUCT_PRICE NUMBER DEFAULT 0,
	PRODUCT_STOCK NUMBER DEFAULT 1
);


CREATE SEQUENCE SEQ_GIFT;
CREATE TABLE TBL_GIFT(
	ID NUMBER CONSTRAINT PK_GIFT PRIMARY KEY,
	GIFT_ADDRESS VARCHAR2(255) NOT NULL,
	GIFT_QTY NUMBER DEFAULT 1,
	PRODUCT_ID NUMBER,
	CONSTRAINT FK_GIFT_PRODUCT FOREIGN KEY(PRODUCT_ID)
	REFERENCES TBL_PRODUCT(ID)
);











































